#!/bin/bash

#SBATCH -e out_%j            # stderr
#SBATCH -o out_%j            # stdout
#SBATCH --mem-per-cpu=300    # memory
#SBATCH -t 00:01:00          # time needed dd-hh:mm:ss
#SBATCH -n 1                 # number of cores
#SBATCH -p test              # queue

echo -e "\n=== Run started $(date) on $HOSTNAME ===\n"

module load intel
./serialexample &> serialexample.out

echo -e "\n=== Run finished $(date) $HOSTNAME ===\n"
