#! /bin/bash

if [ $# -eq 0 ]; then
    cluster="vorna"
else
    cluster=$1
fi

scontrol -M $cluster show node | gawk 'BEGIN {printf("\n")} /^NodeName/ {i=index($1,"=")+1; n=substr($1,i)} /^[ ]+State/ {i=index($1,"=")+1; s=substr($1,i); a[s]++; printf "%-8s %-12s          ",n,s; if (++k%4==0) printf"\n"} END {printf "\n\n"; for (i in a) printf "%-18s %6s\n",i,a[i]; printf "\n"}'

