#! /bin/bash



if [ $# -eq 0 ]; then
    cluster="vorna"
else
    cluster=$1
fi

scontrol -M $cluster show node | gawk 'BEGIN {FS="[= ]+"} $1=="NodeName" {n=$2} /CPULoad/ {printf "%-8s %6.2f\n",n,$9}'
