#! /bin/bash

if [ $# -eq 0 ]; then
    cluster="vorna"
else
    cluster=$1
fi
squeue -a -o "%8u %12T %.10C" | \
gawk 'BEGIN {printf "user           runs  slots  cores/run\n-------------------------------------\n"} $2=="PENDING" {j0++; c0+=$NF; j[$1]++;c[$1]+=$NF} END {for (u in j) printf "%-12s %6d %6d  %6.2f\n",u,j[u],c[u],c[u]/j[u]|"sort"; printf "%-12s %6d %6d  %6.2f\n","TOTAL",j0,c0,c0/(j0>0?j0:1)}'
